image: docker

variables:
  REDIS_HOST: SECURE
  REDIS_POST: SECURE
  MONGO_HOST: SECURE
  MONGO_PORT: SECURE
  BOT_KEY: SECURE
  USE_WEBHOOK: SECURE
  AWS_SECRET_ACCESS_KEY: SECURE
  AWS_ACCESS_KEY_ID: SECURE
  BASE_URL: SECURE
  PAYPAL_ENV: SECURE
  PAYPAL_CLIENT_ID: SECURE
  PAYPAL_CLIENT_SECRET: SECURE



all:
  only:
    - master
  script:
    - echo "REDIS_HOST=$REDIS_HOST" >> .env
    - echo "REDIS_POST=$REDIS_POST" >> .env
    - echo "MONGO_HOST=$MONGO_HOST" >> .env
    - echo "MONGO_PORT=$MONGO_PORT" >> .env
    - echo "BOT_KEY=$BOT_KEY" >> .env
    - echo "USE_WEBHOOK=$USE_WEBHOOK" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "BASE_URL=$BASE_URL" >> .env
    - echo "PAYPAL_ENV=$PAYPAL_ENV" >> .env
    - echo "PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID" >> .env
    - echo "PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET" >> .env
    - cat .env
    - npm install
    - npm test
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN -e cigit@nowhere.org registry.gitlab.com
    - docker build -t registry.gitlab.com/gumino-node-apps/astone-bot .
    - docker push registry.gitlab.com/gumino-node-apps/astone-bot

